name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
    VERSION: 1.0.${{ github.run_number }}
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup Golang
          uses: actions/setup-go@v5
          with:
            go-version: 1.23
        - name: Build
          run: |
            make build
        - name: Test
          run: |
            make test
